name: Archive Binary

permissions:
  actions: write

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  schedule:
      - cron: "0 0 * * *"
jobs:
  build-package:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: dls
            output_binary_name: dml-server-x86_64-gnu
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            binary: dls
            output_binary_name: dml-server-x86_64-musl
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            binary: dls.exe
            output_binary_name: dml-server.exe
            target: x86_64-pc-windows-msvc
    uses: ./.github/workflows/binaries.yml
    with:
      binary_name: ${{ matrix.binary }}
      output_binary_name: ${{ matrix.output_binary_name }}
      target: ${{ matrix.target }}
      log-dir: ${{ matrix.binary }}-logs
      os: ${{ matrix.os }}
  check-package:
    uses: ./.github/workflows/scans.yml
    with:
      os: ubuntu-latest
      log-dir: checking-logs
  merge-package:
    runs-on:
      - ubuntu-latest
    needs: build-package
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: dml-server
          pattern: dml-server-*
